kernel:
  image: okernel:latest
  cmdline: "console=tty0 page_poison=1"
init:
  - linuxkit/init:e0dced91adbfba34c53cd673760e011f410638ff
  - linuxkit/runc:e05648668932e0f1691f40f00ebd14170464577b
  - linuxkit/containerd:cf158d5f56c5b4867f29f0fc3ec49ea505e99333
  - linuxkit/ca-certificates:v0.6
onboot:
  - name: sysctl
    image: linuxkit/sysctl:v0.6
services:
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.6
  - name: getty
    image: linuxkit/getty:2eb742cd7a68e14cf50577c02f30147bc406e478
    env:
     - INSECURE=true
trust:
  org:
    - linuxkit
