kernel:
  image: "linuxkitprojects/kernel-memorizer:4.10_dbg-17e2eee03ab59f8df8a9c10ace003a84aec2f540"
  cmdline: "console=ttyS0"
init:
  - linuxkit/init:e0dced91adbfba34c53cd673760e011f410638ff
  - linuxkit/runc:b87c49e73eb14ba73d23eabf75423e987a043209
  - linuxkit/containerd:cf158d5f56c5b4867f29f0fc3ec49ea505e99333
onboot:
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.6
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
  - name: getty
    image: linuxkit/getty:2eb742cd7a68e14cf50577c02f30147bc406e478
    env:
     - INSECURE=true
trust:
  org:
    - linuxkit
