kernel:
  image: linuxkit/kernel:4.14.89
  cmdline: "console=ttyS0"
init:
  - linuxkit/init:c563953a2277eb73a89d89f70e4b6dcdcfebc2d1
  - linuxkit/runc:83d0edb4552b1a5df1f0976f05f442829eac38fe
  - linuxkit/containerd:326b096cd5fbab0f864e52721d036cade67599d6
onboot:
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.6
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: mount-vpnkit
    image: alpine:3.8
    binds:
        - /var/:/host_var:rbind,rshared
    capabilities:
        - CAP_SYS_ADMIN
    rootfsPropagation: shared
    command: ["sh", "-c", "mkdir /host_var/vpnkit && mount -v -t 9p -o trans=virtio,dfltuid=1001,dfltgid=50,version=9p2000 port /host_var/vpnkit"]
services:
  - name: sshd
    image: linuxkit/sshd:c4bc89cf0d66733c923ab9cb46198b599eb99320
  - name: vpnkit-forwarder
    image: linuxkit/vpnkit-forwarder:v0.6
    binds:
        - /var/vpnkit:/port
    net: host
    command: ["/vpnkit-forwarder"]

files:
  - path: root/.ssh/authorized_keys
    source: ~/.ssh/id_rsa.pub
    mode: "0600"
    optional: true

trust:
  org:
    - linuxkit
